### ISSUE TITLE
question about zone files

### ISSUE THREAD

**Issue by shea256** [jcnelson/blockstack-tor#1]
Awesome work on this @jcnelson!

I have a question about the zone files. Here's the example in the readme:

```
$ORIGIN duckduckgo_tor.id
$TTL 3600
tor TXT "3g2upl4pq6kufc4m.onion"
```

Is this introducing a new "tor" type? If so, shouldn't it be capitalized like this: "TOR"? And will this be a problem for legacy compatibility with traditional zone file parsers and resolvers?

**Comment by jcnelson** [comment]
It conforms to the TXT record specification, so legacy compatibility won't be a problem.  `tor` is just the value of the name column of the RR (i.e. its fully-qualified domain name would be `tor.duckduckgo_tor.id`).  Capitalization doesn't matter for names in DNS.

**Comment by shea256** [comment]
Ah yes right, got confused for a second, thank you. Closing this issue.
